dsherret/dax

src/shell.ts

fix(GH-9): close subprocess stdin after write

---

README.md
mod.test.ts
mod.ts

feat: support providing an array of expressions as arguments

---

README.md
mod.test.ts
mod.ts
src/command.ts
src/common.test.ts
src/common.ts

feat: add `$.setPrintCommand(true)` to mutate print command configuration for a `$`

---

README.md
deno.json
mod.test.ts
src/command.ts
src/command_handler.ts
src/commands/export.ts
src/shell.ts

This is an attempt to get rid of the warnings
This PR:
- fix easy ones
- silence warnings for lines that seems can't be changed
- Add TODO for things I don't get yet
Overall is this a good thing ? I'm not really sure, but on the advantage at least now with 0 warnings you can add deno lint to ci, which would mandate it on PRs

fix or silence all lints

---

.github/workflows/ci.yml
dprint.json

depends on https://github.com/dsherret/dax/pull/33

Add lint to the ci

---

README.md
mod.test.ts
src/command.ts
src/commands/pwd.test.ts
src/commands/pwd.ts

fix https://github.com/dsherret/dax/issues/41

feat: add pwd command

---

README.md
mod.test.ts
mod.ts
src/console/confirm.test.ts
src/console/confirm.ts
src/console/logger.ts
src/console/mod.ts
src/console/progress/interval.ts
src/console/progress/mod.test.ts
src/console/progress/mod.ts
src/console/utils.ts

In the future we should have some functionality for displaying the count a certain way (ex. display bytes as megabytes).
Closes #12
https://user-images.githubusercontent.com/1609021/209868671-71cbbf6c-2e3f-4a5b-b8ca-016736cd1409.mp4

feat: progress bars

---

README.md
mod.ts
src/console/progress/mod.ts
src/request.ts

feat: ability to easily show a progress bar with `$.request`

---

src/console/progress/format.test.ts
src/console/progress/format.ts
src/console/progress/mod.test.ts
src/console/progress/mod.ts
src/request.ts

feat: ability to format value in progress bars as bytes

---

src/deps.test.ts
src/request.test.ts
src/request.ts

feat: `$.request` - `pipeTo` and `pipeThrough`

---

src/request.test.ts
src/request.ts

fix: `$.request` was not cancelling the body on non-200 status code

---

README.md
deno.json
mod.test.ts
mod.ts

feat: ability to add extra methods to `$`

---

README.md
src/common.ts

Uses same example as zx does https://github.com/google/zx
Closes #85

docs: add parallel example

---

src/path.test.ts
src/path.ts

Want this to more easily investigate #118

feat: PathRef - add custom inspect implementation

---

src/path.test.ts
src/path.ts

feat: PathRef - `walk` and `emptyDir`

---

src/path.test.ts
src/path.ts

perf: PathRef - set self as "known resolved" when resolving returns back the same path

---

deno.json

or do you want to keep a minimal working deno version ?

update to deno.json new fmt flat settings

---

src/path.test.ts
src/path.ts

fix: copyFileToDir should be async

---

src/path.test.ts
src/path.ts

fix: appending to files

---

mod.test.ts
src/shell.ts

fix: improve error message when launching command and cwd does not exist

---

README.md

docs: update global `setPrintCommand` docs

---

src/path.test.ts
src/path.ts

fix: `PathRef#withExtname` should allow setting no extension

---

mod.ts

fix: better logging of objects

---

src/command.ts
src/path.ts
src/pipes.ts
src/request.ts

This is for an upcoming perf feature in Deno.

chore: more explicit types

---

README.md
deno.json
mod.test.ts
mod.ts
src/command.ts
src/pipes.ts
src/shell.ts

feat(commands): support providing a `PathRef` to `.stdout(...)` and `.stderr(...)`

---

mod.ts
src/pipes.ts
src/result.ts

Still have 45 errors when running `deno doc --lint mod.ts`. Here's a little bit of a contribution to working that down.

docs: more jsdocs

---

mod.test.ts
src/shell.ts

fix: actually implement pipe sequences

---

mod.test.ts

Test for https://github.com/dsherret/dax/pull/248

chore: test for cat with absolute path

---

mod.test.ts
src/shell.ts

It was throwing an error for some reason.

fix: not finding a command should error in the shell

---

README.md
src/request.test.ts
src/test/server.deno.ts

docs: add `$.escapeArg`

---

README.md
src/path.test.ts
src/path.ts

feat: Path - add `linkTo` and `linkToSync`

---

mod.test.ts
src/shell.ts

fix: providing paths with backslashes on windows

---

src/console/select.ts

fix: allow one option in maybeSelect

---

.github/workflows/ci.yml
deno.json
deno.lock
mod.test.ts
src/command.ts
src/common.ts
src/request.test.ts

Found this in my working tree... can't remember writing this.

fix: remove dep on jsr:@std/streams

---

mod.ts
src/command.ts
src/command_handler.ts
src/commands/executable.ts
src/pipes.ts
src/shell.ts

This is also used internally for launching executables.

feat: add `createExecutableCommand` for creating commands that launch an exectuable

---

README.md

Closes https://github.com/dsherret/dax/issues/280

docs: document default exit code behaviour
