src/commands/cd.ts, src/common.test.ts, src/common.ts
Simple bug fix to allow the `cd` command to support absolute paths, instead of only paths relative to the CWD.
@dsherret I'll do the `~` thing in a separate PR; tests will obviously be a lot more involved given differences in platform.
=> fix: support absolute paths in `cd` command

mod.test.ts, src/commands/exit.ts, src/shell.ts
I just wanted to say this is a great little project, thanks for contributing it!  It's coming in quite handy for a little project I am working on for migrating from `go-task`.
I came across a bug while trying to use `cd` -- it assumes that all paths are relative to the CWD, which obviously leads to some weird behaviour when you do feed it absolute paths.  I just added a quick check to leave absolute paths alone if provided, and that seems to do the trick.
I also needed `exit` and various incantations of `test` for my use case, so I added them as well.  I know its a new project and that you're planning on adding support for more of the commands within `deno_task_shell` at some point, so maybe these aren't exactly what you're looking for.. but they fit the bill for my use case, so I thought …
=> feat: `exit` command

README.md, mod.test.ts, src/commands/test.ts, src/common.ts, src/shell.ts
This PR adds some limited support for a `test` command:
* `test -e <arg>` - argument exists
* `test -f <arg>` - argument is a regular file (not a directory or symlink)
* `test -d <arg>` - argument is a directory
* `test -s <arg>` - argument is non-zero sized
* `test -L <arg>` - argument is a symlink
@dsherret I could use some guidance on the symlink tests -- I have them ~commented out~ excluded on Windows for the moment as apparently you need Administrative rights to create a symlink:
```
test command => dax/mod.test.ts:180:6
error: Error: A required privilege is not held by the client. (os error 1314), symlink 'zero.dat' -> 'linked.dat'
await Deno.symlink('zero.dat', 'linked.dat');
^
at async Object.symlink (deno:runtime/js/30_fs.js:367:5)
at async file:///C:/ ... /dax/mod.test.ts:183:3 …
```
=> feat: add `test` command

README.md, mod.test.ts, mod.ts, src/command.ts, src/command_handler.ts, src/commands/cd.ts, src/commands/echo.ts, src/commands/exit.ts, src/commands/export.ts, src/commands/sleep.ts, src/commands/test.ts, src/deps.test.ts, src/shell.ts
As mentioned in #7, it'd be nice to extend the shell parser to be able to handle additional commands as though they were built-ins/in the system path.  Here's a quick take at implementing support by means of extending the `CommandBuilder` with a `handle()` method for registering a custom command handler/callback.  This should fit in nicely with the custom builder pattern outlined in the documentation.
PR is not so much WIP as at a point where I could use some feedback:
* does this fit with the direction you want things to go?  I tried to be somewhat "non-invasive" in terms of how I implemented this, but as its a new project you may have already had ideas on how you wanted to implement this sort of thing down the road.
* not sure I like `handle`, but `command()` is obviously taken and …
=> feat: support for custom commands

README.md, mod.test.ts, src/command.ts, src/pipes.ts, src/shell.ts
This changes stdout and stderr to be inherited by default. There are several reasons for doing this:
1. It's more efficient.
1. I find myself writing a lot of commands without needing to capture the majority of the time.
1. There are now helper methods like ``const text = await `some_command`.text()``, which will automatically capture when necessary and people should prefer using those.
1. Helps keep stdout and stderr printed in order (https://github.com/dsherret/dax/issues/17)
=> feat: inherit by default for stdout and stderr

mod.test.ts, src/command.ts, src/shell.ts
I think previously I just did something lazy.
=> fix: evaluate real environment on each command execution rather than once on startup

README.md, deno.lock, mod.test.ts, src/command.ts, src/commands/args.test.ts, src/commands/args.ts, src/commands/rm.test.ts, src/commands/rm.ts
I'm not sure how to fix the formatting I tried to use dprint --config but it still the same thing
Deno.remove folds force and recursive into one option recursive, is it ok to expose only `--recursive` ?
=> feat: add `rm` command

src/command.ts, src/console/mod.ts, src/console/progress/interval.ts, src/console/progress/mod.test.ts, src/console/progress/mod.ts, src/deps.ts, src/pipes.test.ts, src/pipes.ts
This should just work:
```ts
const name = await $.prompt("What's your name?");
await $.progress("Running command...").with(async () => {
// this here should work
await $`sleep 1s && echo Hello, ${name}! && sleep 1s && echo Hello again!`;
});
```
=> fix: progress bars should not conflict with inherited command pipes

README.md, src/request.test.ts, src/request.ts
```ts
const url = "https://dl.deno.land/release/v1.29.1/deno-x86_64-unknown-linux-gnu.zip";
await $.request(url)
.showProgress()
.pipeToPath("./deno-x86_64-unknown-linux-gnu.zip");
```
Closes #54
=> feat: `$.request` - `pipeToPath`

README.md, mod.test.ts, src/console/logger.ts, src/console/progress/interval.ts, src/console/progress/mod.ts, src/console/utils.ts
Also, breaking change on `pb.forceRender()` function and `pb.with`, which are both now fully async.
Closes #57
=> fix: better handling for if terminal supports progress bars and selecion

README.md, mod.test.ts, src/command.ts, src/common.test.ts, src/common.ts, src/deps.ts, src/request.test.ts, src/shell.ts
Supports shebangs the same way on all platforms:
```ts
#!/usr/bin/env -S deno run
console.log(5);
```
```ts
await $`./file.ts`; // outputs: 5
```
=> feat: cross platform shebang support

src/request.test.ts, src/request.ts
Just noticed this while looking at the past review. I think it would be better to resolve the path immediately in case someone changes the cwd while the fetch is running.
=> fix: resolve the path immediately in pipeToPath

src/request.test.ts, src/request.ts
Also, cancel request body when pipeToPath throws.
=> feat(request): pipeToPath - support providing single WriteFileOptions argument

src/request.test.ts, src/request.ts
I'm not 100 % confident of the patch but it seems to work
=> fix: handle pipeToPath(undefined, opts) correctly

README.md, src/command.ts, src/console/confirm.test.ts, src/console/logger.ts, src/console/multiSelect.test.ts, src/console/progress/interval.ts, src/console/progress/mod.test.ts, src/console/progress/mod.ts, src/console/prompt.test.ts, src/console/select.test.ts, src/console/testUtils.ts, src/console/utils.ts, src/lib/mod.ts, src/shell.ts
Too much of a hassle to not do this.
=> refactor: use a top level await for the wasm instance to improve the api

README.md, mod.test.ts, mod.ts, src/deps.ts
Thank you very much for `dax`! I really love using it and it has been rock solid as a basis for a rewrite I've just completed of my dotfiles repository (https://github.com/andrewbrey/dotfiles). As you can see if you poke around that repo, it's a lot more than _just_ dotfiles - it's more like a personal toolkit to take a computer from fresh OS install to set up exactly as I prefer.
In creating this repo, I found myself wishing that `dax` had  _just a few_ more helpers dangling off of `$` because of how ubiquitous the `$` import was in my modules and how commonly I encountered a few things like:
- Check if a path is missing (the inverse of `$.exists`)
- Check if a command is defined/undefined (based off of `$.which`)
- Check if an environment variable is well defined
- De-indent (dedent) …
=> feat: add `$.commandExists`, `$.dedent`, and `$.stripAnsi`

mod.test.ts, mod.ts, src/command.ts, src/request.ts
Just thought of this afterwards.
=> feat: `$.commandExists` should take into account registered commands on the `$`

README.md, mod.test.ts, src/command.ts
It's better for this to be explicit in order to not be needlessly done. Additionally, this will make adding streaming support easier.
=> feat: explicit capturing of the combined stdout and stderr

mod.test.ts, src/shell.ts
=> fix: `exit` command should work in boolean list if not first item

README.md, mod.test.ts, src/command.ts, src/command_handler.ts, src/commands/sleep.ts, src/deps.ts, src/pipes.ts, src/result.ts, src/shell.ts
Adds a new `CommandChild` struct that's returned from `.spawn()` that has `.stdout()` and `.stderr()` as well as `.abort()`.
=> feat: add streaming api for command inputs and outputs

src/common.ts, src/request.test.ts, src/request.ts
wget errors in this case, I thought this is an intuitive behavior, not sure if there are disadvantages to this approach
=> fix: handle directory specified for pipeToPath

README.md, src/command.ts, src/request.ts
Supports providing a string like:
```ts
const result = await requestBuilder
.url("https://example.com")
.timeout("10s")
.text();
```
=> feat: support providing a delay to `RequestBuilder#timeout`

src/common.test.ts, src/common.ts
You can now provide values like:
- `timeout("1m")`
- `timeout("2m10s")`
- `timeout("1.5h")`
- `timeout("2h10m")`
- `timeout("2h5m20s")`
=> feat: add minutes and hours to `Delay` options

mod.test.ts, src/commands/rm.ts
This PR adds a try/catch inside `executeRemove` and ignores NotFound errors when `force` is set.
This is inline with the behavior of `rm -Rf` on Unix.
=> fix(rm): ignore `NotFound` errors when `--force` flag is set

mod.test.ts, src/commands/cp_mv.ts, src/common.ts
The test case shows the problematic usage
This whole path manipulation is really fragile, I wonder if there is a guideline somewhere on how to handle this, at least in case of dax we have tests
Note: 
rustJoin in dax seems to have a different result then the actual rust join
rust
```rust
In: Path::new("/tmp/88032199/a/d2").join("/tmp/88032199/a/d1/f")
Out: "/tmp/88032199/a/d1/f"
```
deno: rustJoin
```ts
rustJoin("/tmp/88032199/a/d2", "/tmp/88032199/a/d1/f")
"/tmp/88032199/a/d2/d1/f"
```
not sure if its important or not
=> fix: copy path resolution

README.md, mod.test.ts, mod.ts, src/command.ts, src/common.ts, src/deps.test.ts, src/deps.ts, src/path.test.ts, src/path.ts, src/request.test.ts, src/request.ts
To add in the future:
* components(): Iterator<string>
* startsWith(text: string): boolean;
* endsWith(text: string): boolean;
* link / linkSync
Closes https://github.com/dsherret/dax/issues/94
=> feat: path API

README.md, mod.test.ts, mod.ts
The new path API is much better so this isn't necessary anymore.
=> refactor: remove `$.exists/existsSync(...)` - Use `$.path(...).existsSync()`

src/path.test.ts, src/path.ts
This is a little sketchy to do. See more details in code comment.
=> feat(pathref): add custom instanceof which will work between versions

README.md, src/path.test.ts, src/path.ts
This stores a boolean in the path ref to know that it's resolved. It's about 200ns faster on a short path I measured (will be even faster for longer paths) and returns back `this` when the current `PathRef` is already resolved and no path segments are provided.
=> perf(path_ref): cache if the path is known to be resolved

src/path.test.ts, src/path.ts
It's easier when this is recursive by default.
Note: We should not make `remove` recursive by default though because we don't want to accidentally delete more than we should.
=> feat: `PathRef` - make `mkdir` recursive by default

README.md, mod.ts, src/path.test.ts, src/path.ts
Noticed this while reviewing a PR.
=> feat: `PathRef` - support creating via `import.meta` and file url strings

mod.ts, src/path.test.ts, src/path.ts
Removes all symlink creation functions and replaces them with a single `createSymlinkTo`/`createSymlinkToSync` function.
Closes https://github.com/dsherret/dax/issues/115
=> feat: PathRef - simplify symlink creation functions

mod.ts, src/path.test.ts, src/path.ts
I'm not sure what the right choice is here, so I'm changing it to be explicit for the time being.
=> feat: `PathRef.prototype.createSymlinkTo` - require specifying if absolute or relative for `PathRef` and `URL` args

README.md, src/path.test.ts, src/path.ts, src/request.test.ts
I started actually using this and found myself consistently typing `read` before these, getting no results, and being confused.
=> refactor: PathRef - prefix read methods with `read` for discoverability

src/path.test.ts, src/path.ts
I found myself writing stuff like:
```ts
currentDir.join("bin.js").copyFileSync(dprintDir.join("bin.js"));
currentDir.join("install_api.js").copyFileSync(dprintDir.join("install_api.js"));
currentDir.join("install.js").copyFileSync(dprintDir.join("install.js"));
```
This could be simplified to:
```ts
currentDir.join("bin.js").copyFileToDirSync(dprintDir);
currentDir.join("install_api.js").copyFileToDirSync(dprintDir);
currentDir.join("install.js").copyFileToDirSync(dprintDir);
```
=> feat: PathRef.prototype.copyFileToDir

src/path.test.ts, src/path.ts
=> feat: PathRef - renameToDir

src/shell.ts
I believe this is technically more correct.
=> fix: pass clearEnv: true when calling child process

README.md, mod.test.ts, mod.ts, src/command.ts, src/command_handler.ts, src/commands/sleep.ts, src/shell.ts
=> feat: `CommandBuilder` - `abort()` -> `kill(signal?: Deno.Signal)`

README.md, mod.test.ts, mod.ts, src/command.ts, src/command_handler.ts, src/common.ts, src/shell.ts
```ts
import $, { KillSignalController } from "...";
const controller = new KillSignalController();
const signal = controller.signal;
const promise = Promise.all([
$`sleep 1000s`.signal(signal),
$`sleep 2000s`.signal(signal),
$`sleep 3000s`.signal(signal),
]);
$.sleep("1s").then(() => controller.kill());
await promise; // throws after 1 second
```
=> feat: `KillSignalController`

README.md, mod.test.ts, src/command.ts, src/shell.ts
It shouldn't be surfacing the abort exit code, unless a command attempts to run after failure. This will allow people to return and handle different exit codes based on what signal is sent to the command.
I *think* on timeout it should always surface the abort exit code on failure though and not the command's exit code in order for people to easily be able to test for a timeout having occurred.
=> fix: surface command exit code on kill

README.md, mod.test.ts, src/path.test.ts, src/path.ts, src/request.ts
This is probably more appropriate and consistent even though it's more verbose.
=> refactor: rename more synchronous path methods to have `Sync` suffix

src/path.ts
Spotted when reading the docs: https://deno.land/x/dax@0.34.0/src/path.ts?s=PathRef#method_renameSync_0
=> docs: correct `PathRef.prototype.renameSync` docs

README.md, mod.ts, src/deps.ts, src/path.test.ts, src/path.ts
PathRef:
- `startsWith(path: PathRef | URL | string): boolean`
- `endsWith(path: PathRef | URL | string): boolean`
- `components(): Generator<string>`
- `ensureDir(): Promise<this>`
- `ensureDirSync(): this`
- `ensureFile(): Promise<this>`
- `ensureFileSync(): this`
Removes `$.fs` and `$.path` re-exports of deno_std.
Closes #126
Closes #106
Part of #105
=> feat: PathRef improvements and drop deno_std fs & path re-exports

mod.ts, src/command.ts, src/console/mod.ts, src/console/progress/mod.ts, src/console/prompt.ts, src/path.ts, src/request.ts
This was discovered with the new `--lint` flag that's upcoming in Deno 1.38 (`deno doc --lint mod.ts`).
=> fix: export some non-exported types

src/path.ts
This should make it work in old versions of Deno and new versions that have `Symbol.dispose`.
=> feat: extend `Deno.FsFile` from `FsFileWrapper`

mod.test.ts, src/command.ts, src/deps.test.ts, src/pipes.ts
Usage: 
```typescript
import { $ } from "./mod.ts";
await $`echo "Hello, world!"`.stdout(Deno.stderr);
```
=> feat: allow passing writers to `stdout` and `stderr` builder methods

src/command.test.ts, src/command.ts
```ts
import $ from "https://deno.land/x/dax/mod.ts";
import $2 from "./mod.ts"; // this branch
await $2`echo ${`'abc'`}`; // 'abc'
await $`echo ${`'abc'`}`; // error: Uncaught "Expected closing single quote.\n  '\n  ~"
```
=> fix: `escapeArg` was not escaping multiple quotes

mod.test.ts, src/shell.ts
`deno eval ''` should succeed and output nothing.
```ts
await $`deno eval ''`;
// error: the following required arguments were not provided:
// ...
```
```sh
#!/bin/sh
printf '$#: %d\n' $#
for i in "$@"; do
printf '  [%s]\n' "$i"
done
```
```ts
import $ from "https://deno.land/x/dax/mod.ts";
import $2 from "./mod.ts"; // this branch
Deno.env.set("X", "yyy      zzzz");
console.log("master:");
await $`./test.sh`.printCommand();
await $`./test.sh A 'B' "C"`.printCommand();
await $`./test.sh A "" ""`.printCommand();
await $`./test.sh $X"$X"'$X'`.printCommand();
console.log("\n\nPR:");
await $2`./test.sh`.printCommand();
await $2`./test.sh A 'B' "C"`.printCommand();
await $2`./test.sh A '' ""`.printCommand();
await $2`./test.sh $X"$X"'$X'`.printCommand();
console.log("\n\nBash:");
await …
```
=> fix: empty strings were ignored

mod.test.ts, mod.ts, src/command.ts, src/command_handler.ts, src/commands/cat.ts, src/common.ts, src/pipes.ts, src/shell.ts
Since they're sadly deprecated.
=> refactor: switch to local interfaces for `Deno.Reader`, `WriterSync`, `Closer`

src/path.test.ts, src/path.ts
=> feat: `PathRef.prototype.append`

README.md
I often use dax for one of scripts, which I `chmod a+x`. Howevere, I always have to google the appropriate deno hash bang. It feels like including it in the example might save some googleing for someone, and maybe also teach people that they can chmod+x dax scripts?
=> docs: show shebang in the readme

mod.test.ts, src/command.ts, src/deps.ts, src/pipes.ts, src/request.test.ts, src/shell.ts
=> feat: allow providing a `PathRef` for `.stdin(...)`

mod.test.ts, mod.ts, src/command.ts
Adds a new `.pipe(...)` method for piping one command to another. The critical part of this is that `.pipe(...)` returns the provided command and not the original command. This allows for chaining multiple commands together like so:
```ts
const result = const lineCount = await $`echo 1 && echo 2`
.pipe($`wc -l`)
.text(); // text of the result of wc -l
```
---
I was initially thinking this should be:
```ts
await $`echo 1`
.stdout($`deno eval 'await Deno.stdin.readable.pipeTo(Deno.stderr.writable);'`);
```
...however, it gets confusing about what command someone is acting on when both `.stdout` and `stderr` are set and it becomes ambiguous about what the return value of those methods are.
Closes #137
=> feat: add `.pipe(...)` for piping stdout of a command to another command

mod.test.ts, mod.ts, src/command.ts, src/commands/cat.ts, src/pipes.ts, src/shell.ts
Supports pipe sequences like:
```ts
// not that you would run this
await $`echo 1 && echo 2 | cat -`;
```
=> feat: basic support of pipe sequences

README.md, mod.test.ts, src/commands/cat.ts, src/commands/cd.ts, src/commands/cp_mv.ts, src/commands/echo.ts, src/commands/export.ts, src/commands/mkdir.ts, src/commands/printenv.ts, src/commands/pwd.ts, src/commands/rm.ts, src/commands/sleep.ts, src/commands/test.ts, src/commands/touch.ts, src/commands/unset.ts, src/result.ts, src/shell.ts
Instead of writing:
```ts
return {
kind: "continue",
code: 0,
};
```
You can now just do:
```ts
return { code: 0 };
```
=> feat: remove need for `kind: "continue"` in custom commands

mod.test.ts, src/command.ts, src/command_handler.ts, src/commands/cat.ts, src/commands/cd.ts, src/commands/cp_mv.ts, src/commands/echo.ts, src/commands/exit.ts, src/commands/mkdir.ts, src/commands/printenv.ts, src/commands/pwd.ts, src/commands/rm.ts, src/commands/sleep.ts, src/commands/test.ts, src/commands/touch.ts, src/commands/unset.ts, src/pipes.ts, src/shell.ts
Before:
```ts
export interface CommandPipeWriter extends WriterSync {
writeSync(p: Uint8Array): number;
writeText(text: string): void;
writeLine(text: string): void;
}
```
After:
```ts
export interface CommandPipeWriter {
write(p: Uint8Array): Promise<number> | number;
writeText(text: string): Promise<void> | void;
writeLine(text: string): Promise<void> | void;
}
```
For performance, check if the write in a command returns a promise. If it does, then continue async, otherwise continue sync.
Closes https://github.com/dsherret/dax/issues/224
=> refactor(BREAKING): command pipe writes may now return a promise

src/request.test.ts, src/request.ts
Adds the ability to abort a request's response (note: use `.timeout(...)` to do timeouts):
```ts
const response = await $.request("https://plugins.dprint.dev/info.json");
response.abort();
const text = await response.text(); // throws because aborted
```
=> feat: ability to abort request's response

mod.test.ts, src/command.ts
Previously this would just become `[object Object]`.
```ts
const obj1 = {};
assertThrows(
() => $`echo ${obj1}`,
Error,
"Failed resolving expression in command. Provided object does not override `toString()`.",
);
```
=> feat: error when providing an unexpected object that doesn't override `toString()` in a command expr

mod.test.ts, src/shell.ts
```ts
{
const result = await $`(echo 1 && echo 2) | cat -`.text();
assertEquals(result, "1\n2");
}
{
const result = await $`echo 1 && (echo 2 && exit 1 && echo 3) || echo 4`.text();
assertEquals(result, "1\n2\n4");
}
```
=> feat: support subshells

mod.ts, src/common.ts, src/request.test.ts, src/request.ts
Previously it was throwing a string.
=> feat(BREAKING): a timed out `$.request` now throws a `TimeoutError` with a stack

README.md, mod.test.ts, mod.ts, src/command.ts, src/deps.test.ts, src/path.test.ts, src/path.ts, src/pipes.ts, src/request.ts
`PathRef` is still an export for the time being.
Closes https://github.com/dsherret/dax/issues/235
=> feat: rename `PathRef` to `Path`

mod.test.ts, mod.ts, src/command.ts
This is not yet supported. It needs to be awaited:
```ts
const cmd = $`echo 1`;  // should be: const cmd = await $`echo 1`.text();
await $`echo ${cmd}`;
```
=> fix: better error message when providing a command builder to an expr

scripts/build_npm.ts
The npm type declarations were broken because internal types were being stripped.
=> fix: npm type declarations

README.md
I think it was changed at same point but the example said `console.error(2)` and somehow had `result.stderr` as `5`
=> doc: fix incorrect output in an example in README

src/commands/cat.ts
=> fix: proper resolve path in 'cat' built-in command

mod.test.ts, src/command.ts
There's been a few times where I've needed to grab info from stderr and the ergonomics of doing so are much worse than stdout given the lack of helpers for it. I've updated some of the original helpers for stdout to also optionally be used for stderr or both streams combined. 
There's probably a few more tests to write here and I may have missed something. 
Let me know what you think!
=> feat: enable text, lines, and json to pull from stderr or combined buffers

README.md, mod.test.ts, src/command.ts, src/commands/which.ts, src/shell.ts
I need this for verifying the shell is resolving the path to an excutable as I expect.
=> feat: add cross-platform `which` command

mod.test.ts, mod.ts, src/command.ts
Since dax accepts any object with a `toString()` method, that essentially means it accepts any object. So, this is essentially just a documentation change while also not allowing the `undefined` or `null` types.
Closes #254
=> feat: add `TemplateExpr` type

src/path.test.ts, src/path.ts
=> feat(path): `copyFile` -> `copy` and support copying directories

README.md, deno.json
It was creating node_modules directories in the npm folder because of the package.json (future versions of deno won't do this)
=> chore: fix npm publish

mod.test.ts, mod.ts, src/command.ts, src/console/logger.ts
Considered a regression because the documentation had this called without an arg and this was unintended. Seems there was no tests for this method to catch this.
=> fix: regression - `.bytes()` signature should support no argument

mod.test.ts, src/command.ts, src/shell.ts
Solves #63. 
Interplay between `clearEnv` and `exportEnv` proves tricky. I've went with a solution that, when both flags are set:
-  Writes to the env will go through and affect the real env.
-  Reads will not access any values acquired from the ambient environment.
=> feat: `clearEnv` on `CommandBuilder`

deno.json, deno.lock, dprint.json, mod.test.ts, mod.ts, src/shell.ts
```
> deno run asdf.ts
✅ Granted env access.                                                                                                                                                                                                                                                                          
✅ Granted read access to <CWD>.                                                                                                                                                                                                                                                                
✅ Granted read access to "C:\Program Files\PowerShell\7\". …
```
=> feat(windows): request folder permissions when traversing path

src/common.ts
caught when running `deno task test` on deno 2.1.1
=> fix: type errors

README.md
After Deno v2.0.0, `deno add @scope/name` can't work well, the prefix is needed.
So I fixed it.
https://docs.deno.com/runtime/reference/cli/add/
=> docs: fix installation command

src/console/utils.test.ts, src/console/utils.ts
The `stream` option of `TextDecoder#decode` allows us to properly handle multibyte UTF-8 sequences.
:memo: Thanks to [rinsuki's helpful suggestion](https://x.com/428rinsuki/status/1912495808219607231), we were able to make this change quickly.
Fixes #316
=> fix: handle multibyte characters in `$.prompt`

README.md, deno.lock, mod.test.ts, mod.ts, scripts/build_npm.ts
The `$.cd` helper is confusing because it changes the current directory of the process. It's trivial to just call `Deno.chdir` or `process.chdir` instead and nowadays there is `process.chdir(import.meta.dirname)` when wanting to switch the process' cwd to the current script's (previous it was verbose).
https://github.com/dsherret/dax/issues/298
=> fix(BREAKING): remove confusing `$.cd` helper

README.md, mod.test.ts, mod.ts, src/command.ts
```ts
const args = "arg1   arg2";
await $`echo ${$.rawArg(args)} ${args}`; // executes as: echo arg1 arg2 arg1   arg2
```
Closes https://github.com/dsherret/dax/issues/284
=> feat: add `$.rawArg` for not escaping a specific argument

.github/workflows/ci.yml, README.md, mod.test.ts, mod.ts, src/request.test.ts, src/shell.ts
This removes `deno` always resolving to `Deno.execPath()`.
If you want the old behaviour, you can register "deno" as a custom command like so:
```ts
import { build$, CommandBuilder, createExecutableCommand } from "@david/dax";
const $ = build$({
commandBuilder: new CommandBuilder()
.registerCommand("deno", createExecutableCommand(Deno.execPath()))
});
```
Closes https://github.com/dsherret/dax/issues/308
Closes https://github.com/dsherret/dax/issues/297
Closes https://github.com/dsherret/dax/issues/255
=> fix(BREAKING): remove deno as a built-in command

README.md, mod.ts
This allows callback when using `build$`, which allows for building off the current state of the builder (and also reduces the number of imports necessary)
=> feat: allow callbacks for `build$`

mod.test.ts, src/command.ts
There were some bugs caused in Deno's scripts because promises were provided.
=> fix: surface type checking error when erroneously providing a `Promise` in a template literal expr
